### ISSUE TITLE
Is this a `#[no_std]` crate?

### ISSUE THREAD

**Issue by DuckEater54** [carlosgaldino/gotenksfs#2]

**Comment by MahanthMohan** [comment]
This would not be a `![no_std]` crate as the filesystem is a part of userspace. It can make system calls to the underlying OS (Linux/MacOS), that would allow it to mimic the functions of a real filesystem running in kernel space. Therefore, it can make use of the standard libary and its features as it can depend on `std`

**Comment by DuckEater54** [comment]
Okay
