### ISSUE TITLE
Compilation Errors: Mismatched datatypes and unknown fields

### ISSUE THREAD

**Issue by MahanthMohan** [carlosgaldino/gotenksfs#3]
## Erroneous Code Segment
[Code Snippet](https://github.com/carlosgaldino/gotenksfs/blob/9768a65e9cfd911b80fc50009f0e6671a11361ee/src/gotenks/fs.rs#L592-L600)
## Output of command `cargo build`
   Compiling gotenksfs v0.0.0 (/home/mahanth/Documents/src/gotenksfs)
error[E0308]: mismatched types
   --> src/gotenks/fs.rs:592:27
    |
592 |                 f_blocks: sb.block_count,
    |                           ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error[E0308]: mismatched types
   --> src/gotenks/fs.rs:593:26
    |
593 |                 f_bfree: sb.free_blocks,
    |                          ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error[E0308]: mismatched types
   --> src/gotenks/fs.rs:594:27
    |
594 |                 f_bavail: sb.free_blocks,
    |                           ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error[E0308]: mismatched types
   --> src/gotenks/fs.rs:595:26
    |
595 |                 f_files: sb.inode_count,
    |                          ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error[E0308]: mismatched types
   --> src/gotenks/fs.rs:596:26
    |
596 |                 f_ffree: sb.free_inodes,
    |                          ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error[E0308]: mismatched types
   --> src/gotenks/fs.rs:597:27
    |
597 |                 f_favail: sb.free_inodes,
    |                           ^^^^^^^^^^^^^^ expected `u64`, found `u32`

error: cannot construct `libc::statvfs` with struct literal syntax due to inaccessible fields
   --> src/gotenks/fs.rs:589:24
    |
589 |             let stat = libc::statvfs {
    |                        ^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/gotenks/types.rs:307:25
    |
307 |         stat.st_nlink = self.hard_links;
    |                         ^^^^^^^^^^^^^^^ expected `u64`, found `u16`

error[E0609]: no field `st_birthtime` on type `fuse_rs::fs::FileStat`
   --> src/gotenks/types.rs:311:14
    |
311 |         stat.st_birthtime = self.created_at as _;
    |              ^^^^^^^^^^^^ unknown field

Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `gotenksfs` due to 9 previous errors

## Comments
- As per these compiler errors, it seems that the types of the fields of the struct `libc::statvfs` need to be u64 instead of an u32. This can be fixed by doing `stat.field_name = some_value as u64`. 
- Besides, according to the documentation for `libc::statvfs` on [docs.rs](https://docs.rs/libc/latest/libc/struct.statvfs.html), the struct fields are marked with the `pub` identifier, which means they are public and this code segment should be able to access its fields. But, it turns out that there are errors during compile time, which have no possible solution besides just copying the struct definition for `statvfs` to the types.rs file and then importing that. But as `fuse_rs::Result` has a trait bound that only accepts a type that is `libc::statvfs`, this should be fixed through some other approach
- Removal of the [`st_birthtime`](https://github.com/carlosgaldino/gotenksfs/blob/9768a65e9cfd911b80fc50009f0e6671a11361ee/src/gotenks/types.rs#L311) field in the `FileStat` struct returned by the `to_stat` function

**Comment by carlosgaldino** [comment]
This project is being archived.
