### ISSUE TITLE
Bug in test?

### ISSUE THREAD

**Issue by siennathesane** [carlosgaldino/gotenksfs#6]
Hi, I'm using this as a reference example, and I noticed that these two tests keep failing.

https://github.com/carlosgaldino/gotenksfs/blob/9768a65e9cfd911b80fc50009f0e6671a11361ee/src/gotenks/types.rs#L504-L545

Specifically, https://github.com/carlosgaldino/gotenksfs/blob/9768a65e9cfd911b80fc50009f0e6671a11361ee/src/gotenks/types.rs#L510 & https://github.com/carlosgaldino/gotenksfs/blob/9768a65e9cfd911b80fc50009f0e6671a11361ee/src/gotenks/types.rs#L532 are failing. I _think_ they're failing because you subtract `1` from the index when loading the bitvec values, so you're ending up with a double negative value. I fixed the negations in the assertions and that fixed the tests, I was wondering if you'd be able to confirm that is the correct fix?

I know this was a toy, so no worries if you're not sure. Off-by-one errors are brutally difficult to troubleshoot so I figured I'd ask on the off-change you'd be willing to double check :)

**Comment by carlosgaldino** [comment]
Thanks. It's been almost 4 years since I touched this code. I remember at the time all the tests were passing. I'm archiving this repo as I don't intend to make any more changes to it. Good luck!
